
name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: go get .
      working-directory: cli

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Coverage
      run: go test -v -cover ./... -coverprofile coverage.out
      working-directory: cli

    - name: upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: cli/coverage.out
