
name: Build/test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: go get .
      working-directory: cli

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
      working-directory: cli

    - name: Test cli directory
      run: go test -v ./...
      working-directory: cli

    - name: Test data directory
      run: go test -v ./data

